version = 1

test_patterns = ["tests/**"]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"
  [analyzers.meta]
  max_line_length = 200
  runtime_version = "3.x.x"