from enum import Enum


# ==================== Elimination Types ====================

class EliminationReason(Enum):
    """Reasons for miner elimination."""
    ZOMBIE = "ZOMBIE"
    INACTIVE = "INACTIVE"
    PLAGIARISM = "PLAGIARISM"
    MAX_TOTAL_DRAWDOWN = "MAX_TOTAL_DRAWDOWN"
    FAILED_CHALLENGE_PERIOD_TIME = "FAILED_CHALLENGE_PERIOD_TIME"
    FAILED_PROBATION_TIME = "FAILED_PROBATION_TIME"
    FAILED_CHALLENGE_PERIOD_DRAWDOWN = "FAILED_CHALLENGE_PERIOD_DRAWDOWN"
    # INTRADAY/EOD: intraday vs day-open equity, EOD vs EOD high-water mark (trailing). INTRADAY is also the
    # reason for static subaccounts' Rule 2 (the same check with a flat threshold override — see
    # DrawdownCriteria.STATIC handling in MinerBucketState.intraday_drawdown_threshold)
    FAILED_CHALLENGE_PERIOD_INTRADAY_DRAWDOWN = "FAILED_CHALLENGE_PERIOD_INTRADAY_DRAWDOWN"
    FAILED_CHALLENGE_PERIOD_EOD_DRAWDOWN = "FAILED_CHALLENGE_PERIOD_EOD_DRAWDOWN"
    FAILED_FUNDED_PERIOD_INTRADAY_DRAWDOWN = "FAILED_FUNDED_PERIOD_INTRADAY_DRAWDOWN"
    FAILED_FUNDED_PERIOD_EOD_DRAWDOWN = "FAILED_FUNDED_PERIOD_EOD_DRAWDOWN"
    # STATIC: subaccount Rule 1 — equity (incl. unrealized PnL) vs starting balance
    FAILED_CHALLENGE_PERIOD_STATIC_DRAWDOWN = "FAILED_CHALLENGE_PERIOD_STATIC_DRAWDOWN"
    FAILED_FUNDED_PERIOD_STATIC_DRAWDOWN = "FAILED_FUNDED_PERIOD_STATIC_DRAWDOWN"
    # STATIC_EOD: retired — no longer produced, kept only because historical elimination rows may carry this value
    FAILED_CHALLENGE_PERIOD_STATIC_EOD_DRAWDOWN = "FAILED_CHALLENGE_PERIOD_STATIC_EOD_DRAWDOWN"
    FAILED_FUNDED_PERIOD_STATIC_EOD_DRAWDOWN = "FAILED_FUNDED_PERIOD_STATIC_EOD_DRAWDOWN"
    # PRO: same four rules, but for the pro account track
    FAILED_PRO_CHALLENGE_PERIOD_INTRADAY_DRAWDOWN = "FAILED_PRO_CHALLENGE_PERIOD_INTRADAY_DRAWDOWN"
    FAILED_PRO_CHALLENGE_PERIOD_EOD_DRAWDOWN = "FAILED_PRO_CHALLENGE_PERIOD_EOD_DRAWDOWN"
    FAILED_PRO_CHALLENGE_PERIOD_STATIC_DRAWDOWN = "FAILED_PRO_CHALLENGE_PERIOD_STATIC_DRAWDOWN"
    FAILED_PRO_CHALLENGE_PERIOD_STATIC_EOD_DRAWDOWN = "FAILED_PRO_CHALLENGE_PERIOD_STATIC_EOD_DRAWDOWN"
    FAILED_PRO_FUNDED_PERIOD_INTRADAY_DRAWDOWN = "FAILED_PRO_FUNDED_PERIOD_INTRADAY_DRAWDOWN"
    FAILED_PRO_FUNDED_PERIOD_EOD_DRAWDOWN = "FAILED_PRO_FUNDED_PERIOD_EOD_DRAWDOWN"
    FAILED_PRO_FUNDED_PERIOD_STATIC_DRAWDOWN = "FAILED_PRO_FUNDED_PERIOD_STATIC_DRAWDOWN"
    FAILED_PRO_FUNDED_PERIOD_STATIC_EOD_DRAWDOWN = "FAILED_PRO_FUNDED_PERIOD_STATIC_EOD_DRAWDOWN"
    LIQUIDATED = "LIQUIDATED"
    DEREGISTERED = "DEREGISTERED"

    @property
    def is_intraday_drawdown(self):
        return self in (self.FAILED_CHALLENGE_PERIOD_INTRADAY_DRAWDOWN, self.FAILED_FUNDED_PERIOD_INTRADAY_DRAWDOWN,
                        self.FAILED_PRO_CHALLENGE_PERIOD_INTRADAY_DRAWDOWN, self.FAILED_PRO_FUNDED_PERIOD_INTRADAY_DRAWDOWN)

    @property
    def is_eod_drawdown(self):
        return self in (self.FAILED_CHALLENGE_PERIOD_EOD_DRAWDOWN, self.FAILED_FUNDED_PERIOD_EOD_DRAWDOWN,
                        self.FAILED_PRO_CHALLENGE_PERIOD_EOD_DRAWDOWN, self.FAILED_PRO_FUNDED_PERIOD_EOD_DRAWDOWN)

    @property
    def is_static_drawdown(self):
        return self in (self.FAILED_CHALLENGE_PERIOD_STATIC_DRAWDOWN, self.FAILED_FUNDED_PERIOD_STATIC_DRAWDOWN,
                        self.FAILED_PRO_CHALLENGE_PERIOD_STATIC_DRAWDOWN, self.FAILED_PRO_FUNDED_PERIOD_STATIC_DRAWDOWN)

    @property
    def is_static_eod_drawdown(self):
        return self in (self.FAILED_CHALLENGE_PERIOD_STATIC_EOD_DRAWDOWN, self.FAILED_FUNDED_PERIOD_STATIC_EOD_DRAWDOWN,
                        self.FAILED_PRO_CHALLENGE_PERIOD_STATIC_EOD_DRAWDOWN, self.FAILED_PRO_FUNDED_PERIOD_STATIC_EOD_DRAWDOWN)
